services:
  - type: web
    name: marathi-deepfake-detection
    runtime: docker
    repo: https://github.com/drushtantt/Marathi-Deepfake-Detection
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /healthz
